### ISSUE TITLE
Can not initiate a model

### ISSUE THREAD

**Issue by arsenyinfo** [wasidennis/DeepHarmonization#2]
Hi guys, 
Thanks for the interesting paper and released code! 

I've downloaded a model (`harmonize_iter_200000.caffemodel`) but it's not working:
```
root@6400dcb7b629:/DeepHarmonization# python demo.py
...
I0222 20:06:22.437355    17 net.cpp:284] Network initialization done.
I0222 20:06:22.616809    17 net.cpp:791] Ignoring source layer data
I0222 20:06:22.616827    17 net.cpp:791] Ignoring source layer mask_data_1_split
F0222 20:06:22.616842    17 net.cpp:797] Check failed: target_blobs.size() == source_layer.blobs_size() (5 vs. 3) Incompatible number of blobs for layer bn0
*** Check failure stack trace: ***
Aborted (core dumped)
```

Are there any specific requirements I should care about?

**Comment by wasidennis** [comment]
Hi,

I found a post regarding your issue: https://www.bountysource.com/issues/35937456-resnet-50-testing.

What is the caffe version you are using now?
It looks like that your caffe integrates BatchNorm and Scale layers in a single BatchNorm layer, and that's why it shows that the size is not matched.

**Comment by arsenyinfo** [comment]
Hi @wasidennis! Thanks for the rapid reply.

I'm using  caffe from `nvidia/caffe` docker:
```
root@6400dcb7b629:/DeepHarmonization# caffe --version
caffe version 0.15.13
```
Is there a recommended version?

**Comment by wasidennis** [comment]
The official version should work: https://github.com/BVLC/caffe.
From the link I found, in the end it said version 0.16 fixed it, but I am not sure as I am not following caffe now. Or you can try to revise the layer into a single BatchNorm layer as the link mentioned.

Btw, thanks for your interest in using our code.

**Comment by arsenyinfo** [comment]
Using docker image `bvlc/caffe:gpu` solved the problem. Thank you again!
