### ISSUE TITLE
Running demo.py resulting in complete white images

### ISSUE THREAD

**Issue by advaza** [wasidennis/DeepHarmonization#4]
Hi,
I just tried to run the demo.py script, and the results are all white. I wanted to debug it to see the output values before the clipping to 0,255 but I don't see what I'm trying to print (I'm new to caffe - is it not possible to print to std out on inference?).

**Caffe version:** 0.17.0
**Ubuntu**: 16.04.2
**Python**: 2.7.12

Thank you!
Adva

**Comment by wasidennis** [comment]
The demo code is based on python, so you can just print what you need by "print xxx" in demo.py.

**Comment by advaza** [comment]
I did that but the only output I got was the caffe output: model layout + log.

Few lines from the output (out of ~3000 lines):
`
convolution_param {
    num_output: 3
    pad: 1
    kernel_size: 4
    stride: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
'
'
I0706 20:44:08.580144   176 net.cpp:109] Using FLOAT as default forward math type
I0706 20:44:08.580150   176 net.cpp:115] Using FLOAT as default backward math type
`

**Comment by wasidennis** [comment]
It looks like the problem may come from the caffe version. Are you using the official caffe version or the other third-party released ones?

**Comment by advaza** [comment]
I'm using a docker image from nvidia gpu cloud.

**Comment by wasidennis** [comment]
Okay, then you should use an official version of caffe from their website.

**Comment by advaza** [comment]
I tried the official docker image and now it works, thanks!
