### ISSUE TITLE
About your network achitecture

### ISSUE THREAD

**Issue by Dominoer** [wasidennis/DeepHarmonization#8]
Hi, Thanks for your useful code, I have a problem when I trying to reproduce your experiment. 
For the last Conv layer used in the network, you said it's a 4x4 conv layer in your paper, but in your prototxt, it's a fully-connected layer. If you could answer my question, It would be very appreciated.

**Comment by wasidennis** [comment]
The fc layer is the bottle-neck layer (the end of the encoder). If you check the bottom of the prototxt, you will see the harmonization decoder, where the last layer should be (De)Conv.

**Comment by Dominoer** [comment]
Thanks for your answer, I made a mistake. I mean the last layer used in the encoder. but anyway, thank you again!
